all:
	gcc test_list.c -std=gnu99 -g -o test_list -I ../../utils/ -L ../../utils/ -lutils
	gcc test_skiplist.c -std=gnu99 -g -o test_skiplist -I ../../utils/ -L ../../utils/ -lutils

clean:
	rm -f test_list
	rm -f test_skiplist
